services:
  web:
    build: .
    command: gunicorn drama.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://neondb_owner:npg_AS1FxKNqXvD7@ep-plain-bush-a40ffg5t-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require