# Generated by Django 5.2 on 2025-06-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_challenge_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenged_game_type',
            field=models.CharField(blank=True, choices=[('taps', 'Taps'), ('shake', 'Shake')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger_game_type',
            field=models.CharField(blank=True, choices=[('taps', 'Taps'), ('shake', 'Shake')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waiting_for_movie', 'Waiting for Movie Selection'), ('waiting_for_game', 'Waiting for Game Selection'), ('ready_to_play', 'Ready to Play'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
